PROJECT:
  project_name: "DETR for object detection"
  device: cuda
  seed: 42
  model_name: DETR_1
PATH:
  root_dir: /NAS3/Members/linchenxi/projects/object_detection/detr
  output_dir: /NAS3/Members/linchenxi/projects/object_detection/detr
  model_dir: /NAS3/Members/linchenxi/projects/object_detection/detr/model
DATASET:
  coco_path: /NAS3/Members/linchenxi/projects/datasets
  dataset_file: coco
  coco_panoptic_path: null
HYPERPARAM:
  lr: 0.0001
  lr_backbone: 1.0e-05
  batch_size: 24
  weight_decay: 0.0001
  epochs: 300
  lr_drop: 200
  clip_max_norm: 0.1
  frozen_weights: null
  backbone: resnet50
  dilation: false
  position_embedding: sine
  enc_layers: 6
  dec_layers: 6
  dim_feedforward: 2048
  hidden_dim: 256
  dropout: 0.1
  nheads: 8
  num_queries: 100
  pre_norm: false
  masks: false
  aux_loss: true
  set_cost_class: 1
  set_cost_bbox: 5
  set_cost_giou: 2
  mask_loss_coef: 1
  dice_loss_coef: 1
  bbox_loss_coef: 5
  giou_loss_coef: 2
  eos_coef: 0.1
  remove_difficult: false
  resume: ''
  start_epoch: 0
  eval: false
  num_workers: 2
  world_size: 1
  dist_url: env://
  local_rank: 0

  
